# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=26.2
loader_version=0.19.3
# Mod Properties
mod_version=1.1
maven_group=wilpam
archives_base_name=tweaks
# Dependencies
# check this on https://modmuss50.me/fabric.html
fabric_version=0.158.0+26.2
# Polymer (server-side content library)
# check this on https://maven.nucleoid.xyz/eu/pb4/
polymer_version=0.17.3+26.2
